import 'package:alarm_app/core/constants/app_constants.dart';
import 'package:alarm_app/data/models/alarm_model.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:android_alarm_manager_plus/android_alarm_manager_plus.dart';
import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive (local database)
  await Hive.initFlutter();

  // Register the AlarmModel adapter (generated by hive_generator)
  Hive.registerAdapter(AlarmModelAdapter());

  // Open the alarms box
  await Hive.openBox<AlarmModel>(AppConstants.alarmBox);

  // Initialize Android Alarm Manager
  await AndroidAlarmManager.initialize();

  runApp(const AlarmApp());
}